plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

version = '1.0.0'
group = 'com.example.specialforces'

base {
    archivesName = 'special-forces'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets.main.resources { srcDir 'src/generated/resources' }

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', 'specialforces'
        }

        register('client')

        register('server') {
            args '--nogui'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:26.2-65.0.0')
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
        minecraft_version      : '26.2',
        minecraft_version_range: '[26.2,26.3)',
        forge_version          : '65.0.0',
        forge_version_range    : '[65,)',
        loader_version_range   : '[65,)',
        mod_id                 : 'specialforces',
        mod_name               : 'Special Forces',
        mod_license            : 'MIT',
        mod_version            : version,
        mod_authors            : 'vietanhrs',
        mod_description        : 'Adds military weapons and gadgets: Sniper Rifle, Night Vision Goggles, and Bullets.'
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes([
            'Specification-Title'     : 'specialforces',
            'Specification-Vendor'    : 'specialforcesteam',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : 'specialforcesteam',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}
